version: "3"
services:

  tmodloader:
    image: hhhfffted/tmodloader:latest
    restart: unless-stopped
    ports:
      - '7777:7777'
    environment:
      - TERRARIA_VER=1423
      - TMOD_VER=0.11.8.4
      - MODS=TMOD
    volumes:
      - ./terraria:/terraria
    tty: true
    stdin_open: true
    
